language: node_js
sudo: required
node_js:
    - "6"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
script:
    - bash travisGCCExport.bash
    - bash build.bash

