language: node_js
sudo: required
node_js:
- '6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
script:
- bash build.bash
- npm test
deploy:
  provider: releases
  api_key:
    secure: nu5lql2/5O3wLTqoufx/BrgXd3+L/uBbpR2zhDITi9L3PLuiLsE7WZUgiu6hvxyP8jUf5D1t0yIMFG10oW9iD3K4MEtwllOZEa6iupkvuJy51yJXVNUJ0ijAZUtP+vpr79U0vEUrG0sa6V1ZRjCwk59uN+RoyzICHrloTu3gAsToqwDuG/yE1ONTy2TXQfMf4mArZ3ZYrr7BIqab27QMlv8itd9QZxJFXDnpNKsNMii1OoES8i1IoybQdYYVv4NWb6ugm3hDNjx+RUdVAGuxaKhe65Khg3YEYPhClbLUsCavNV7dSbI0k9kVPc5pN0eVCWptY4UYiqcXH8yEb+/iR/QeDkoxYjuMU0SCbU4rDT/CkwD6oFKc/L6yuptX65vHjBqjAGV5cUMp/bCnrq2uskKmhG51qVL8fEPBOdjCuAMpnS6f+miDqN2qZESol2N0eJrbQ9kltMZeYfPTC928dGEZNMP+vgDbSluw7UyZ+7ykHkQHmOKUUwdMIeKL27wSEE4hCeq9+xmT5XqrdYMJKN2H5y+qwKw8dRW8dOfQuMiSKThyxttbg5oQ0mVWsMqreQRL/j3r/I+pkfTPhbwnRjPKjHCP1IwRSg0Rk+X44dxzPp/9Q3PoqecmRe+fIw2QlxHWaOpHVUucxRqWBt7lKU1RpFd10KaDPygWpeWFH7I=
  file: nwsjs
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
