install:
    - cmd: npm install

build_script:
    - bash build.bash APPVEYOR

test_script:
    - cmd: echo Skipped

artifacts:
    - path: nwsjs.exe

deploy:
    provider: GitHub
    force_update: true
    auth_token:
        secure: fqX7hM2PGofEbimvGZVHX3VfHeKE+IFOQUOH/W96SWtmZNG+nUgou9zbCt6RA5j9
        artifact: /nwsjs.exe/
    on:
        appveyor_repo_tag: true
